### ISSUE TITLE
CUP Specification File Errors

### ISSUE THREAD

**Issue by asison19** [asison19/lexical-analyzer#2]
When compiling parser.cup with CUP, these errors arise:

Error: Syntax error @ Symbol: CLASS (unknown:16/38(-1) - unknown:16/43(-1))
instead expected token classes are []
Error : Illegal use of reserved word
Error: Syntax error @ Symbol: EXTENDS (unknown:16/57(-1) - unknown:16/64(-1))
Error : Internal error: Unexpected exception
Exception in thread "main" java.lang.NullPointerException
        at java_cup.runtime.lr_parser.symbl_name_from_id(lr_parser.java:456)
        at java_cup.runtime.lr_parser.report_expected_token_ids(lr_parser.java:446)
        at java_cup.runtime.lr_parser.syntax_error(lr_parser.java:433)
        at java_cup.runtime.lr_parser.parse(lr_parser.java:725)
        at java_cup.Main.parse_grammar_spec(Main.java:496)
        at java_cup.Main.main(Main.java:196)

**Comment by asison19** [comment]
Rename terminals and nonterminals to all uppercase equivalents?
Doing so creates new errors:

Warning : Scanner at 40(17): Unrecognized character '+' -- ignored
Warning : Scanner at 61(21): Unrecognized character '+' -- ignored
Error: Syntax error @ Symbol: COMMA (unknown:61/21(-1) - unknown:61/22(-1))
Error : Internal error: Unexpected exception
Exception in thread "main" java.lang.NullPointerException
        at java_cup.runtime.lr_parser.symbl_name_from_id(lr_parser.java:456)
        at java_cup.runtime.lr_parser.report_expected_token_ids(lr_parser.java:446)
        at java_cup.runtime.lr_parser.syntax_error(lr_parser.java:433)
        at java_cup.runtime.lr_parser.parse(lr_parser.java:725)
        at java_cup.Main.parse_grammar_spec(Main.java:496)
        at java_cup.Main.main(Main.java:196)
